version: '3.0'
networks:
  elk:
    driver: bridge

volumes:
  esdata:

services:
#===============================================================================#
# ELK Stack                                                                     #
#===============================================================================#
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0
    environment:
      ES_JAVA_OPTS: "-Xmx${ES_RAM}m -Xms${ES_RAM}m"
    restart: unless-stopped
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
#    ports:
#      - "9200:9200"
    networks:
      - elk