version: '3.0'
networks:
  elk:
    driver: bridge

volumes:
  esdata:

services:
#===============================================================================#
# ELK Stack                                                                     #
#===============================================================================#
  elasticsearch:
    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      ES_JAVA_OPTS: "-Xmx${ES_RAM}m -Xms${ES_RAM}m"
    restart: unless-stopped
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
#    ports:
#      - "9200:9200"
    networks:
      - elk

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.5.2
#    image: docker.elastic.co/kibana/kibana-oss:7.5.2
    restart: unless-stopped
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: logstash/
    restart: unless-stopped
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./opt/logstash-forwarder.crt:/etc/logstash/pki/logstash-forwarder.crt:ro
      - ./opt/logstash-forwarder.key:/etc/logstash/pki/logstash-forwarder.key:ro
        # Temporary, til I figure out a process to download new databases weekly
      - ./logstash/maxmind/GeoLite2-City_20180807:/etc/maxmind:ro
    ports:
      # Syslog
      - "5043:5043"
      - "6043:6043"
      # Metricbeat
      - "5044:5044"
      - "6044:6044"
      # Winlogbeat
      - "5045:5045"
      - "6045:6045"
      # Filebeat
      - "5046:5046"
      - "6046:6046"
    environment:
      LS_JAVA_OPTS: "-Xmx${LS_RAM}m -Xms${LS_RAM}m"
      LS_METRICBEAT_DROP_RATE: "${LS_METRICBEAT_DROP_PERCENTAGE}"
    networks:
      - elk


# Used for loading initial index templates, dashboards, also provides monitoring#
#===============================================================================#
  metricbeat:
    container_name: metricbeat
    build:
      context: metricbeat/
    networks:
      - elk
    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
